### ISSUE TITLE
Logo null?

### ISSUE THREAD

**Issue by derekantrican** [viceroypenguin/Going.Plaid#115]
The following code:
```csharp
var result = await PlaidClient.InstitutionsGetByIdAsync(new Going.Plaid.Institutions.InstitutionsGetByIdRequest()
{
    InstitutionId = "ins_3",
    CountryCodes = new[]
    {
        Going.Plaid.Entity.CountryCode.Us,
    },
    Options = new Going.Plaid.Entity.InstitutionsGetByIdRequestOptions
    {
        IncludeOptionalMetadata = true,
    },
});
```

Gives the following result:
```json
{
  "Institution": {
    "InstitutionId": "ins_56",
    "Name": "Chase",
    "Products": [
      0,
      1,
      2,
      8,
      9,
      10,
      3,
      4,
      5
    ],
    "CountryCodes": [
      0
    ],
    "Url": "https://www.chase.com",
    "PrimaryColor": "#095aa6",
    "Logo": null,
    "RoutingNumbers": [
      "021000021",
      "021100361",
      "021202337",
      "022300173",
      "028000121",
      "044000037",
      "051900366",
      "061092387",
      "065400137",
      "071000013",
      "072000326",
      "074000010",
      "075000019",
      "083000137",
      "102001017",
      "103000648",
      "111000614",
      "122100024",
      "123271978",
      "124001545",
      "267084131",
      "322271627",
      "325070760"
    ],
    "Oauth": false,
    "Status": null,
    "PaymentInitiationMetadata": null,
    "AuthMetadata": null
  },
  "RawJson": null,
  "Error": null,
  "RequestId": "yxx4CaHA59uJpAd",
  "StatusCode": 200,
  "IsSuccessStatusCode": true
}
```

(Note that `Logo` is null)

According to the [docs](https://plaid.com/docs/api/institutions/#institutionsget)

"`include_optional_metadata`: When true, return the institution's homepage URL, logo and primary brand color."

`Logo` still seems to be null in the above response. The docs state that it _can_ be nullable, but I figure for a institution as large as Chase it probably isn't. Can you doublecheck that your library is correctly passing the `Logo` value back in the response?

**Comment by viceroypenguin** [comment]
I'm sorry to say that `Logo` is not provided by Plaid for `ins_3`. If you set `client.ShowRawJson = true;`, you can see the raw json that is provided by the Plaid servers, and you'll notice that the `logo` field is specifically `null`. You should raise this with Plaid.

![image](https://user-images.githubusercontent.com/1992555/207425269-d4248b30-fb71-40f0-93f7-12e9031707b7.png)

**Comment by derekantrican** [comment]
@viceroypenguin - gotcha, thanks! Also good to know about `client.ShowRawJson` - I'll definitely be using that!

**Comment by viceroypenguin** [comment]
You bet! I hope it helps!

Just would recommend you don't use `client.ShowRawJson` in production, as it reduces performance of response parsing and increases memory pressure. Without `ShowRawJson`, we use the System.Text.Json serializer directly on the target response object, which means it can parse streaming the data directly from the response stream. With `ShowRawJson`, we buffer the response into a `string`, and then deserialize the `string`. In most cases, it probably won't have an impact on performance, but best practices and all that.
