### ISSUE TITLE
Unsupported Error Codes

### ISSUE THREAD

**Issue by jason-rohman** [viceroypenguin/Going.Plaid#149]
It looks like there may be some new error codes that aren't supported in Going.Plaid.
I'm not sure when Plaid added it, but here is the one that's causing me issues: [invalid_webhook_verification_key_id](https://plaid.com/docs/errors/invalid-input/#invalid_webhook_verification_key_id)

**Comment by viceroypenguin** [comment]
Thanks for the update. Unfortunately, these are not tracked in the openapi spec, so I don't have any automated awareness of changes. I'll work on this today.

**Comment by viceroypenguin** [comment]
v5.0.0 is released; the properties are changed to `string`, so that matching an enum is no longer a problem. This is per discussion with the Plaid team.
