### ISSUE TITLE
String '2023-04-07T21:44:44Z' contains parts which are not specific to the DateOnly. 

### ISSUE THREAD

**Issue by apereladov** [viceroypenguin/Going.Plaid#181]
Going.Plaid.Entity.ConnectedApplication {
	[JsonPropertyName("created_at")]
	public DateOnly CreatedAt { get; init; } = default!;
}

Plaid response is 
![image](https://github.com/viceroypenguin/Going.Plaid/assets/149167042/3879f403-d11a-4b3b-be9a-800d45b69af6)

**Comment by viceroypenguin** [comment]
Hello @apereladov. This is a bug in the in the upstream OpenAPI spec file distributed by Plaid. I have escalated this issue to them, and they have agreed to add correct this in the spec file in the November release; at which point I will update this library based on that release. If you need a fix sooner, please let me know and they have agreed with me to do a mid-month release including this fix.

**Comment by viceroypenguin** [comment]
This field has been corrected in Going.Plaid and released with v6.10.0
