### ISSUE TITLE
Please add method for /item/application/unlink endpoint 

### ISSUE THREAD

**Issue by apereladov** [viceroypenguin/Going.Plaid#182]
![image](https://github.com/viceroypenguin/Going.Plaid/assets/149167042/bd3991c2-48c2-4b6d-8f65-55907851da21)

**Comment by viceroypenguin** [comment]
Hello @apereladov. This API is not currently present in the upstream OpenAPI spec file distributed by Plaid. I have escalated this issue to them, and they have agreed to add this api to the spec file in the November release; at which point I will update this library based on that release. If you need a fix sooner, please let me know and they have agreed with me to do a mid-month release including this API.

**Comment by viceroypenguin** [comment]
This endpoint has been added to Going.Plaid and released with v6.10.0
