### ISSUE TITLE
LinkTokenCreateRequest does not accept Language as an enum but string.

### ISSUE THREAD

**Issue by netsharpdev** [viceroypenguin/Going.Plaid#218]
There is a Language enum that is not used in the LinkTokenCreateRequest. So whenever I want to set language I need to pass a string to the request which is frustrating, because I don't want to use reflection on the enum due to the performance drawbacks.

**Comment by viceroypenguin** [comment]
Which version of Plaid are you on? The current version (v6.18.0) correctly uses the `Language` enum, as you can see here: https://github.com/viceroypenguin/Going.Plaid/blob/master/src/Plaid/Link/LinkTokenCreateRequest.cs#L19

**Comment by netsharpdev** [comment]
Oh, indeed. I have had 6.16.0 version. Thanks!
