### ISSUE TITLE
Consumer Report Permissible Purpose Object 

### ISSUE THREAD

**Issue by saugatp11** [viceroypenguin/Going.Plaid#263]
https://github.com/viceroypenguin/Going.Plaid/blob/master/src/Plaid/Entity/LinkTokenCreateRequestConsumerReportPermissiblePurposeObject.cs

This is the link to the file.

LinkTokenCreateRequest class, type for ConsumerReportPermissiblePurpose is changed to Entity.LinkTokenCreateRequestConsumerReportPermissiblePurposeObject which was earlier an ENUM but now the new class/type doesn't have any value/property in the class
 
[JsonPropertyName("consumer_report_permissible_purpose")]
public Entity.LinkTokenCreateRequestConsumerReportPermissiblePurposeObject? ConsumerReportPermissiblePurpose { get; set; } = default!;

**Comment by viceroypenguin** [comment]
Addressed in db9a7a8ab75909059317550708df1b1c05badec8, released as v6.31.1.
