### ISSUE TITLE
CRA Report PDF Endpoint

### ISSUE THREAD

**Issue by saugatp11** [viceroypenguin/Going.Plaid#266]
I didn't see an implementation for this, is it possible to add this endpoint to PlaidClient.

https://github.com/viceroypenguin/Going.Plaid/blob/master/src/Plaid/Cra/PlaidClient.cs

https://plaid.com/docs/check/api/#cracheck_reportpdfget
/cra/check_report/pdf/get

**Comment by viceroypenguin** [comment]
Available with v6.31.3, releasing now.
