### ISSUE TITLE
Support additional User properties when creating a link token

### ISSUE THREAD

**Issue by grcodemonkey** [viceroypenguin/Going.Plaid#39]
Plaid API version **2020-09-14** supports several properties that are missing in the `Going.Plaid.Entity.User` class

https://plaid.com/docs/api/tokens/#link-token-create-request-user

Currently the class only exposes the required **client_user_id** property, but the API supports other optional fields such as legal_name, phone, email, etc...

**Comment by viceroypenguin** [comment]
If you would like to add them, I'll take a PR? I might have time for this next week if not.

I have a side-project to automate creating all of the entities directly from their .yaml file [here](https://github.com/plaid/plaid-openapi) (now that it's available), but until then, it's manual.

**Comment by grcodemonkey** [comment]
PR up https://github.com/viceroypenguin/Going.Plaid/pull/40

**Comment by viceroypenguin** [comment]
Released via v2.6.0
