### ISSUE TITLE
Improve support for .net core 3.1

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/Going.Plaid#44]
@walltechco reports that there are issues using Going.Plaid w/ .net core 3.1 (and possibly earlier) due to use of certain c#9 features. This library should properly support .net core 3.1. This issue tracks any missing support items.

**Comment by walltechco** [comment]
The primary issue I ran into when running on .NET Core 3.1 was the use of `init;` only setters and `record` types that were both added in C#9 and not available in .NET Core 3.1.

**Comment by viceroypenguin** [comment]
I just downgraded my personal project to .net core 3.1 and was able to build and run just fine. Can you be more specific with how `init;` and `record` types are not working with your code in .net core 3.1?

**Comment by QuanTran91** [comment]
I got the issue "nuget package downgrade detected" when trying to install version 2.6.0

**Comment by viceroypenguin** [comment]
@QuanTran91 - Addressed in #45. Will do preview release (is also technically a breaking change)

**Comment by viceroypenguin** [comment]
Release under v2.7.0
