### ISSUE TITLE
Install in Web-Application

### ISSUE THREAD

**Issue by BigShorty01** [viceroypenguin/Going.Plaid#46]
I wanted to install it in my Web Application but it fails. 
---
`Das Paket "Going.Plaid 2.6.0" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf ".NETFramework,Version=v4.5" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.`			
---
I have tried switching to different target frameworks but none I seleceted works. 
What tartget framework is needed?

**Comment by viceroypenguin** [comment]
Going.Plaid targets a minimum of .net core 3.1, sorry.
