### ISSUE TITLE
Unity support?

### ISSUE THREAD

**Issue by SavedByZero** [viceroypenguin/Going.Plaid#52]
Any chance there are steps that will get this to work properly with Unity?

**Comment by viceroypenguin** [comment]
I do not have any steps specifically, no. I have never tried it. I don't see any reason it would not work, though. Please give it a try, and if you face any issues, I'll be glad to review with you and help get it working. Let me know!

**Comment by SavedByZero** [comment]
Thank you. One issue I’m seeing is that Unity complains about a ton of redundant dll files when I use nuGet to install the other plaid plugin, and this one doesn’t even get that far. My initial question is — will this work with .net 4.x? The Going Plaid nuGet install fails with a message saying that “the package does not contain any assembly references or content files that are compatible with that framework”, referring to my c# solution that Unity targets to .net 4.7.1.

**Comment by viceroypenguin** [comment]
This library specifically supports only .net core 3.1, .net 5, and .net 6. I do not have any support for .net fx 4.7.1, nor do I plan to. Also, it appears that Unity recommends that async/await is not used in Unity scripting - doing web api  calls from .net is generally recommended to do via async/await, and all of the calls from this library are done that way. This may in fact be incompatible with a proper Unity environment. More research would be required.

**Comment by SavedByZero** [comment]
Okay, I’ll try the Acklann library again, though I suspect it will have similar concerns with Unity.

**Comment by viceroypenguin** [comment]
I have updated release version 4.2.0 to include back-support for .net standard 2.0, which should allow it to be supported on 4.7.1.

**Comment by viceroypenguin** [comment]
Were you able to get Plaid working in Unity? Can I close this issue?

**Comment by SavedByZero** [comment]
Hey — sorry about that; I had to explore other native plugins because I began realizing that Unity has some unique issues when it comes to installing standard .net libraries, and I only just came back to this now. I am going to try this one more time over the next day or two and see how it goes — otherwise this could just be marked as “Unity is too messy to handle this without dedicated research”.

**Comment by SavedByZero** [comment]
Addendum:  -I got it to compile in Unity by just adding all the proper dlls from the nuget install into a "packages" folder  INSIDE the Assets folder (i.e. moving them from the root "packages" folder into Assets/packages), while carefully avoiding duplicates; only the ones in the standard 2.0 lib folders should be passed.  

That being said, compatibility across native platforms (Android and iOS) is still an open question as there would need to be some way to embed the Link widget into Going-Plaid without relying on a browser, which the API doesn't seem to support as of now?

**Comment by viceroypenguin** [comment]
Yeah, the Link Widget is definitely a private component of Plaid, so there's no plan to provide any alternative to it. Even in desktop situations, it can be handled via WebView2 control or similar. I'm not sure how to trigger a browser popup in a phone environment, but I know I have seen applications do it, so it should be possible? Would probably be a native API or an abstraction of such.

**Comment by SavedByZero** [comment]
As I work on this — what do I do to get the Link widget showing up with this library?  The readme  shows how to set up a basic client instance, but the part about requesting a link token and opening a link widget with this api is what I’m still fuzzy on.
