### ISSUE TITLE
Get Access Token?

### ISSUE THREAD

**Issue by omiddehghan2036** [viceroypenguin/Going.Plaid#53]
Hello
How can i get access token ?

**Comment by omiddehghan2036** [comment]
I want test library in Sandbox Environment.

**Comment by viceroypenguin** [comment]
@omiddehghan2036  - there is a demo project in the source code that can be used as an example of how to use Plaid. You will need to provide the information from the keys page of the Plaid login. Once filled in, it can show you how to get the link tokens and trade them for access tokens. Review [this](https://github.com/viceroypenguin/Going.Plaid/blob/master/tests/Plaid.Demo/Controllers/HomeController.cs) controller and [this](https://github.com/viceroypenguin/Going.Plaid/blob/master/tests/Plaid.Demo/Views/Home/Index.cshtml) view specifically for more detailed information. 

Notice the order of operations: 
1. Reference the Plaid JS and open a Plaid link dialog. 
2. Take the link token given by a successful link and hand it to the web server. 
3. Take the link token and hand it to Plaid in exchange for an access token.  

Let me know if you need any more help.
