### ISSUE TITLE
CategoriesGetAsync - Plaid returns "invalid fields" error

### ISSUE THREAD

**Issue by joshgreenwald** [viceroypenguin/Going.Plaid#54]
According to Plaid, a client_Id and secret should not be passed to the Plaid API, as categories/get does not take any parameters and should be called anonymously.

**Comment by viceroypenguin** [comment]
Sure enough. I'll get it corrected shortly. Sorry about that!

**Comment by joshgreenwald** [comment]
Thank you! I'm getting by with calling categories/get with a vanilla HttpClient, so no rush!

**Comment by viceroypenguin** [comment]
Check out version 4.3.0, just released. Should be fixed now! Thanks for reporting!
