### ISSUE TITLE
'System.DateOnly' instances are not supported - Path: $.Transactions.AuthorizedDate.

### ISSUE THREAD

**Issue by christopherfowers** [viceroypenguin/Going.Plaid#58]
Ran into this issue. Probably user error. I wrote this kind of quick and dirty to test things out. Having a problem when trying to pull transactions with a valid accessToken and a known accountId. 

### What happened: 

```
System.NotSupportedException: Serialization and deserialization of 'System.DateOnly' instances are not supported. The unsupported member type is located on type 'System.Nullable`1[System.DateOnly]'. Path: $.Transactions.AuthorizedDate.
```

### My code: 

```
public async Task<TransactionsGetResponse> GetTransactions(string accessToken, string accountId)
{
    return await _client.TransactionsGetAsync(
        new() {
              AccessToken = accessToken,
              StartDate = DateOnly.FromDateTime(DateTime.Now.AddDays(DateTime.Now.Day * -1)),
              EndDate = DateOnly.FromDateTime(DateTime.Now),
              Options = new TransactionsGetRequestOptions 
              {
                  AccountIds = new [] 
                  {
                      accountId
                  },
                  Count = 500
              }
        });
}
```

**Comment by christopherfowers** [comment]
Ok so big oof. This was my own API Controller not able to parse this. Going.Plaid seems to be doing it's job just fine. Its trying to use the plaid output in my API that is the real issue here. I can solve this. Probably wont as I was only doing this for a quick and dirty test and don't actually want that data going out to a client anyway.

**Comment by viceroypenguin** [comment]
Ah. That makes more sense. Was trying to figure out how the serializer did not get attached.  FYI: there is a serializer already in the package designed to handle the above, which you can attach to your serializer options if you want. Look at `Going.Plaid.Converters.DateTimeConverter`, and at the extension method: `System.Text.Json.PlaidExtensions.AddPlaidConverters()`. This will only add converters to a specific options object, not the global one, but it can be useful. I believe you can modify the options for the asp.net api in the Startup() method.

**Comment by christopherfowers** [comment]
Yeah... Definitely user error. I did see the Parser in the readme. Thank you!

**Comment by christopherfowers** [comment]
Also for anyone who has this sort of question come up and wants an example of what @viceroypenguin is talking about I'll drop a quick note here: 

If you want to have your controller actions return a Going.Plaid object in the response, you can simply update your controller configuration to something like this

```
services.AddControllers()
    .AddJsonOptions(j =>
    {
        j.JsonSerializerOptions.AddPlaidConverters();
    });
``` 

Basically what is in the readme.
