### ISSUE TITLE
Missing client method for /asset_report/pdf/get

### ISSUE THREAD

**Issue by jcoliz** [viceroypenguin/Going.Plaid#63]
Is there a way to contact the [/asset_report/pdf/get](https://plaid.com/docs/api/products/assets/#asset_reportpdfget) endpoint using Going.Plaid? If so, please point me in the right direction, thanks!

**Comment by viceroypenguin** [comment]
Ah, currently, no. I'm currently only automating the `application/json` api calls... see [here](https://github.com/viceroypenguin/Going.Plaid/blob/c040063c7433015ffe43a1506dd3529542e727b9/src/Plaid.OpenApiParser/Program.cs#L90). At the time, I didn't want to deal with the complexity of figuring out the API for the pdfs, and I never got back to it. I can review next week and add it, unless you get it done first.

**Comment by jcoliz** [comment]
Gotcha. It's not urgent. Just was working on completeness to match the official quickstart, which does download an asset report PDF.

**Comment by jcoliz** [comment]
@viceroypenguin I started looking at this. The first thing I did was `dotnet run` in the `Plaid.OpenApiParser` directory. This changed 8 files and create one new one in the `Plaid` directory. Then when building from the `Plaid` directory, many many errors were reported.

Am I approaching this the correct way?

**Comment by viceroypenguin** [comment]
Definitely on the right track, however, the parser is not a complete one, it gets me 90% of the way there and then I massage a few things back into place after running it. Namely the `Error` property on several objects and there's one object that tries to inherit from `string`... It got to a point where I decided my time was better spent fixing the errors manually than trying to fix the parser to be perfect. Alas.

**Comment by jcoliz** [comment]
Ok, so perhaps it would be better to start by writing direct code to handle the PDF endpoint? Not worrying about the parser. That's definitely easier, though comes with the risk that the upstream API moves around.

**Comment by viceroypenguin** [comment]
I would say for now, yeah; that's what I was planning on doing at first for sure. 

1. Add another method to `ResponseParser` to return a `Stream`
2. Add another file under AssetReports dir for PlaidClients.Manual.cs (i'm open to suggestions on the filename here), and put the API call there.

Thoughts?

**Comment by jcoliz** [comment]
We'll need more than a stream, we also need the content headers. In fact, we probably have to take ownership of the entire httpresponse, else disposing the response will dispose our stream. NSwag creates a FileResponse class for this, which I like.

What would you think of integrating a bit more tightly to what you have already, to reduce outliers and repetition?

AssetReportPdfGetAsync could live right next to AssetReportGetAsync for easy finding:

```c#
	public Task<FileResponse> AssetReportPdfGetAsync(AssetReport.AssetReportPdfGetRequest request) =>
		PostAsync("/asset_report/pdf/get", request)
			.ParseResponseAsync<FileResponse>();
```

By using the existing ParseResponse, BuildResponse code, we get the advantage of the existing logging and error checking.

```c#
		private readonly async Task<TResponse> BuildResponse<TResponse>(HttpResponseMessage response) where TResponse : ResponseBase, new()
		{
			if (response.IsSuccessStatusCode)
			{
				if (IncludeRawJson)
				{
				  // ...
				}
				else if (typeof(TResponse).IsSubclassOf(typeof(FileResponse)))
				{
				  // Create a FileResponse here

```

(Also don't quote me on the `typeof(TResponse)` bit, I haven't compiled that yet 😁)

The tricky bit is telling ParseResponseAsync not to dispose the response, which likely means putting a property in ResponseBase. Alternately, could create a totally new ParseFileReponse, however then all the error handling and logging of Parse/BuildResponse have to be duplicated.

**Comment by jcoliz** [comment]
Oh wait, I get it. PlaidClient.Manual.cs is needed because next run of API parser will overwrite PlaidClient.cs.

**Comment by viceroypenguin** [comment]
Honestly, the only part that would really be shared between the json and the stream version is the error code. I'd say we take the error code into a function, call it from where it is now as well as from an error branch of a new function, and return a `FileResponse` from there. I don't care if the logging code has to be duplicated, because even that will likely have variances from the existing code. I should probably update the logging code anyway at some point to use the new source generators, which would reduce the duplication of that code.

**Comment by viceroypenguin** [comment]
The new source generator version of logging is only supported in .net 6, so nevermind on that prticular part.
