### ISSUE TITLE
Link Token Update

### ISSUE THREAD

**Issue by momin4073** [viceroypenguin/Going.Plaid#68]
Error Message : account select update is not supported for the assets product

Can anyone please let me know what is the fix for this issue?
I am trying to update link token.

Here is the Error Infromation
![image](https://user-images.githubusercontent.com/38028840/172903670-f64f7106-73f6-40ac-bcbc-d1b2ecc7bbea.png)
I am not passing any products in the request for this.

Here is my implementation

```csharp
var request = new Going.Plaid.Link.LinkTokenCreateRequest();
                var updateAccountSelection = new Going.Plaid.Entity.LinkTokenCreateRequestUpdate();
                updateAccountSelection.AccountSelectionEnabled = true;
                request.ClientId = "ClientId";
                request.Secret = "ClientSecret";
                request.ClientName = "Client Name";
                request.User = user;
                request.CountryCodes = Enum.GetValues(typeof(Going.Plaid.Entity.CountryCode)).Cast<Going.Plaid.Entity.CountryCode>().Where(x => x.ToString() == "Us").ToList();
                if (accessToken != "")
                {
                    request.AccessToken = accessToken;
                    request.Update = updateAccountSelection;
                }
                    
                else
                    request.Products = Enum.GetValues(typeof(Going.Plaid.Entity.Products)).Cast<Going.Plaid.Entity.Products>()
                        .Where(x => x.ToString() == "Assets" || x.ToString() == "Auth").ToList();

                var result = await client.LinkTokenCreateAsync(request);
```

**Comment by viceroypenguin** [comment]
Thank you @momin4073 for creating the separate issue. 

I have not seen this specific error message, but based on the message, I think there are two possible issues here:
* Your account is not currently enabled for `asset` products. This is a separate feature that needs to be enabled by the Plaid team, so you would need to discuss with them about enabling assets for your account.
* When you originally created the token, you did not ask for assets on the token. You cannot add additional products to a token after it has been created. If you want to add assets to the token, you will need to remove the existing `Item` (access-token) and start with a new login for the token.

**Comment by momin4073** [comment]
Thank you @viceroypenguin for the detailed reply,
I need to use the following products

- Identity
- Auth
- Balance

Can you please let me know which products should I write to create Link Token based on Going.Plaid ? I was using Acklan.Plaid previously and the implementation was a bit different.

**Comment by viceroypenguin** [comment]
If those are the only products you need, then you should request those specifically, as follows: 

```csharp
using Going.Plaid.Entity; // at top of file
request.Products = new[] { Products.Identity, Products.Auth, Products.Balance, };
```

**Comment by viceroypenguin** [comment]
If you would like example code, you may checkout this repository: https://github.com/jcoliz/PlaidQuickstartBlazor

There is a working demo, along with the code supporting the demo, which you can read to write code for your system.

**Comment by momin4073** [comment]
One small thing when we add Products.Balance for the first time in to create Link Token it throws the following error
![image](https://user-images.githubusercontent.com/38028840/172910905-86096aa6-c500-41e6-bb39-2810e9ea7309.png)

**Comment by viceroypenguin** [comment]
Ah, sorry. I screwed that up. Don't provide Balance. Per doc: "balance is not a valid value, the Balance product does not require explicit initialization and will automatically be initialized when any other product is initialized."

**Comment by momin4073** [comment]
Got it. Thanks for the help :)

**Comment by viceroypenguin** [comment]
Glad to help! Feel free to re-open if you have any other issues.
