### ISSUE TITLE
Going.Plaid Please Remove FlowType field, cannot do

### ISSUE THREAD

**Issue by HitchHikerOfGalaxies** [viceroypenguin/Going.Plaid#93]
First of all thank you for developing this package for C# as it has been a tremendous help for our user's to manage their financial data. I was updating the code for our project which uses Going.Plaid for our back end and would send in Auth requests with the following request: 

 Going.Plaid.Entity.LinkTokenCreateRequestUser user = new Going.Plaid.Entity.LinkTokenCreateRequestUser();
 Going.Plaid.Entity.LinkTokenCreateRequestAuth auth = new Going.Plaid.Entity.LinkTokenCreateRequestAuth();
 auth.AutomatedMicrodepositsEnabled = true;

var plaidClient = new PlaidClient(
Going.Plaid.Environment.Production,
secret: ourSecret,
clientId: ourClientID);
Going.Plaid.Link.LinkTokenCreateRequest request = new Going.Plaid.Link.LinkTokenCreateRequest();

request.ClientName = clientName;
request.ClientId = ourClientID
request.Products = new Going.Plaid.Entity.Products[] { Going.Plaid.Entity.Products.Auth, Going.Plaid.Entity.Products.Transactions };
request.User = user;
request.Secret = ourSecret;
request.Language = Going.Plaid.Entity.Language.English;
request.CountryCodes = new Going.Plaid.Entity.CountryCode[] { Going.Plaid.Entity.CountryCode.Us };
request.Auth = auth;

var ourLinkToken = plaidClient.LinkTokenCreateAsync(request);
return Json(new { ourLinkToken }); //once returned in frontend, work with token 

Everything works fine until reaching authorization which results in error code 27 after receiving the result of the request above in our front end. The error message from said request mentions a flow_type field: 'auth type select should only be enabled with the auth_type_select_enabled field, please remove the flow_type field'. This error would not occur in August and I am assuming Plaid is just updating their API recently and with that come certain errors like this one.

I checked to see if I could remove this myself but sadly this can't be done on my end as the class is coming in from the nuget package. I noticed this data type was disabled in one of your commits a little over 2 weeks ago and was wondering if this fixes my issue and when the latest version will be available for download via nuget (https://www.nuget.org/packages/Going.Plaid)?

**Comment by viceroypenguin** [comment]
Thanks for the comments. Apologies for the error - it's been a busy few weeks. I'm planning to spend some OSS time this weekend - should be able to fix it then with v4.15.0. v4.12.0 should work fine until then. Hope this helps. I'll let you know when I've got a new release out.

**Comment by HitchHikerOfGalaxies** [comment]
Thank you so much for the quick response! No need to apologize as you're providing a great service here and completely understand being overhauled with work. I just tested v4.12 and it works great. Looking forward to the future updates and hope you have a great weekend.

**Comment by viceroypenguin** [comment]
Version 4.15.0 has been released which includes latest changes from Plaid; the fix has been restored into this version as well.

**Comment by HitchHikerOfGalaxies** [comment]
Just upgraded to 4.15 and no issues! Thank you so much.
